/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package arszamolo;

import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kovács Bálint
 */
public class FoAblak extends javax.swing.JFrame {

    // Globális változók:
    Termek[] termekek = new Termek[100];
    int termekekSzama = 0;

    DefaultTableModel termekekModel;

    /**
     * Creates new form FoAblak
     */
    public FoAblak() {
        initComponents();

        termekekModel = (DefaultTableModel) tblTermekek.getModel();
        tblTermekek.setModel(termekekModel);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblTermekek = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfTermekNeve = new javax.swing.JTextField();
        tfBeszerzesiAr = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnFelvitel = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tfArres = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnArresModositasa = new javax.swing.JButton();
        btnRendezes = new javax.swing.JButton();
        btnLegolcsobb = new javax.swing.JButton();
        btnLegdragabb = new javax.swing.JButton();
        btnAtlag = new javax.swing.JButton();
        btnTorol = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblTermekek.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Termék neve", "Beszerzési ár", "Eladási ár"
            }
        ));
        jScrollPane1.setViewportView(tblTermekek);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Új termék"));

        jLabel1.setText("Termék neve:");

        jLabel2.setText("Beszerzési ár:");

        jLabel3.setText("Ft");

        btnFelvitel.setText("Felvitel");
        btnFelvitel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFelvitelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfTermekNeve, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfBeszerzesiAr, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addComponent(btnFelvitel, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfTermekNeve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfBeszerzesiAr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)))
            .addComponent(btnFelvitel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Árrés"));

        jLabel4.setText("Árrés:");

        tfArres.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfArres.setText("15");

        jLabel5.setText("%");

        btnArresModositasa.setText("Árrés módosítása");
        btnArresModositasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArresModositasaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfArres, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(btnArresModositasa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfArres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnArresModositasa, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnRendezes.setText("Rendezés termék neve szerint");
        btnRendezes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRendezesActionPerformed(evt);
            }
        });

        btnLegolcsobb.setText("Legolcsóbb termék");
        btnLegolcsobb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLegolcsobbActionPerformed(evt);
            }
        });

        btnLegdragabb.setText("Legdrágább termék");
        btnLegdragabb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLegdragabbActionPerformed(evt);
            }
        });

        btnAtlag.setText("Átlag termékár (eladási)");
        btnAtlag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtlagActionPerformed(evt);
            }
        });

        btnTorol.setText("Sor Törlése");
        btnTorol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTorolActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRendezes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLegolcsobb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLegdragabb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAtlag, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTorol)
                .addGap(222, 222, 222))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRendezes, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLegolcsobb, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLegdragabb, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAtlag, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnTorol)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRendezesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRendezesActionPerformed
        for(int i=termekekSzama;i>1;i--){
             for(int j=0;j<i-1;j++){
                 int compare = termekek[j].getTermekNev().compareTo(termekek[j+1].getTermekNev());
                 if(compare>0){
                     Termek cs = termekek[j];
                    termekek[j] = termekek[j+1];
                    termekek[j+1] = cs;
                 }
             }
         }
        
        /*for (int i=0; i<=termekekSzama-2; i++) {
            for (int j=i+1; j<=termekekSzama-1; j++) {
                int compare = termekek[i].getTermekNev().compareTo(termekek[j].getTermekNev());
                if (compare>0) {
                    Termek cs = termekek[i];
                    termekek[i] = termekek[j];
                    termekek[j] = cs;
                }
            }
        }*/
        int arres = Integer.parseInt(tfArres.getText());
        termekekModel.setRowCount(0);
        for (int i = 0; i < termekekSzama; i++) {

            int beszerzesiAr = termekek[i].getBeszerzesiAr();
            float eladasiAr = beszerzesiAr + beszerzesiAr * ((float) arres / 100);
            
            //tblTermekek.removeAll();
             termekekModel.addRow(new Object[]{termekek[i].getTermekNev(),termekek[i].getBeszerzesiAr(),eladasiAr});
            

        }
       
        
    }//GEN-LAST:event_btnRendezesActionPerformed

    private void btnLegolcsobbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLegolcsobbActionPerformed
        int min = 0;

        for (int i = 1; i < termekekSzama; i++) {
            if (termekek[i].getBeszerzesiAr() < termekek[min].getBeszerzesiAr()) {
                // Innen hiányzik valami:
                min = i;
            }
        }
        JOptionPane.showMessageDialog(this, "A legolcsóbb termék: " + termekek[min].getTermekNev() + "(" + termekek[min].getBeszerzesiAr() + ")");
    }//GEN-LAST:event_btnLegolcsobbActionPerformed

    private void btnLegdragabbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLegdragabbActionPerformed
        int max = 0;

        for (int i = 1; i < termekekSzama; i++) {
            if (termekek[i].getBeszerzesiAr() > termekek[max].getBeszerzesiAr()) {
                // Innen hiányzik valami:
                max = i;
            }
        }
        JOptionPane.showMessageDialog(this, "A legdrágább termék: " + termekek[max].getTermekNev() + "(" + termekek[max].getBeszerzesiAr() + ")");
    }//GEN-LAST:event_btnLegdragabbActionPerformed

    private void btnAtlagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtlagActionPerformed
      float atlag = 0;
      int arres = Integer.parseInt(tfArres.getText());
      
            
      

        for (int i = 1; i < termekekSzama; i++) {
            int beszerzesiAr = termekek[i].getBeszerzesiAr();
            float eladasiAr = beszerzesiAr + beszerzesiAr * ((float) arres / 100);
           atlag += eladasiAr;
        }
        atlag = atlag/termekekSzama;
        JOptionPane.showMessageDialog(this,"Átlag termékár: "+atlag);
    }//GEN-LAST:event_btnAtlagActionPerformed

    private void btnFelvitelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFelvitelActionPerformed
        // 1. Adatok kiolvasása a beviteli mezőkből (2db) és elhelyezésük változókban:
        String nev = tfTermekNeve.getText();
        int beszerzesiAr = Integer.parseInt(tfBeszerzesiAr.getText());

        // 2. A kiolvasott adatok alapján a termekek és termekekSzama globális változók módosítása:
        // (ez a lépés összevonható az 1.-vel)
        termekek[termekekSzama] = new Termek(nev, beszerzesiAr);
        termekekSzama++;

        // 3. Eladási ár kiszámolása a beolvasott beszerzési árból és az árrés mező tartalmából:
        int arres = Integer.parseInt(tfArres.getText());
        float eladasiAr = beszerzesiAr + beszerzesiAr * ((float) arres / 100);

        // 4. Sor hozzáadása a táblázathoz:
        // TODO: a három érték helyére a fent kiszámítottak kerüljenek (változók)
        termekekModel.addRow(new Object[]{nev, beszerzesiAr, eladasiAr});
    }//GEN-LAST:event_btnFelvitelActionPerformed

    private void btnArresModositasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArresModositasaActionPerformed
        // TODO: Táblázat újrarajzolása a termekek globális tömb és az új
        // árrés érték segítségével:
        int arres = Integer.parseInt(tfArres.getText());
        for (int i = 0; i < termekekSzama; i++) {

            int beszerzesiAr = termekek[i].getBeszerzesiAr();
            float eladasiAr = beszerzesiAr + beszerzesiAr * ((float) arres / 100);
            /*termekekModel.setRowCount(0);
             termekekModel.addRow(new Object[]{termekek[i].getTermekNev(),termekek[i].getBeszerzesiAr(),eladasiAr});*/
            termekekModel.setValueAt(eladasiAr, i, 2);

        }


    }//GEN-LAST:event_btnArresModositasaActionPerformed

    private void btnTorolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTorolActionPerformed
    int torlendo = tblTermekek.getSelectedRow();
     //JOptionPane.showMessageDialog(this,torlendo);
    Termek[] termekek_uj = new Termek[100];
    int j=0;
    for (int i = 0; i < termekekSzama; i++) {
        if(i!=torlendo){
            termekek_uj[j]=termekek[i];
            j++;
        }
    }
    //JOptionPane.showMessageDialog(this,j);
    Arrays.fill(termekek, null);
    
    System.arraycopy( termekek_uj, 0, termekek, 0, j );
    
   
    termekekSzama = j;
    
    /*TEST LIST*/
    int arres = Integer.parseInt(tfArres.getText());
        termekekModel.setRowCount(0);
        for (int i = 0; i < termekekSzama; i++) {

            int beszerzesiAr = termekek[i].getBeszerzesiAr();
            float eladasiAr = beszerzesiAr + beszerzesiAr * ((float) arres / 100);
            
            //tblTermekek.removeAll();
             termekekModel.addRow(new Object[]{termekek[i].getTermekNev(),termekek[i].getBeszerzesiAr(),eladasiAr});
            

        }
    
    //termekekModel.removeRow(torlendo);
   
    
    }//GEN-LAST:event_btnTorolActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FoAblak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FoAblak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FoAblak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FoAblak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FoAblak().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArresModositasa;
    private javax.swing.JButton btnAtlag;
    private javax.swing.JButton btnFelvitel;
    private javax.swing.JButton btnLegdragabb;
    private javax.swing.JButton btnLegolcsobb;
    private javax.swing.JButton btnRendezes;
    private javax.swing.JButton btnTorol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTermekek;
    private javax.swing.JTextField tfArres;
    private javax.swing.JTextField tfBeszerzesiAr;
    private javax.swing.JTextField tfTermekNeve;
    // End of variables declaration//GEN-END:variables
}
